if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="powerlevel10k/powerlevel10k"

# Sauce
[[ ! -f "${HOME}/.p10k.zsh" ]] || source "${HOME}/.p10k.zsh"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="false"

# Uncomment one of the following lines to change the auto-update behavior
zstyle ':omz:update' mode auto

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 1

export UPDATE_ZSH_DAYS=13
export ZSH_CUSTOM_AUTOUPDATE_QUIET=true

# Plugins
  plugins=(
  aliases
  autoupdate
  aws
  brew
  dirhistory
  docker
  kubectl
  kubectx
  git
  golang
  history
  macos
  minikube
  ripgrep
  rsync
  shellfirm
  sudo
  terraform
  zsh-completions
)

source "${ZSH}/oh-my-zsh.sh"

(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[path]=none

ZSH_HIGHLIGHT_STYLES[path_prefix]=none

eval "$(zoxide init zsh)"
eval "$(thefuck --alias)"
